---

- name: run whoami
  command: whoami
  changed_when: false
  register: whoami

- name: check if difrectory to store Emacs source code exists
  stat:
    path: '{{ src_dir }}'
  register: src_dir_stat
  become: true

- name: make sure directory to store Emacs source code exists
  file:
    group: '{{ whoami.stdout }}'
    mode: 0775
    owner: '{{ whoami.stdout }}'
    path: '{{ src_dir }}'
    state: directory
  become: true
  when: not src_dir_stat.stat.exists

- name: download source code
  unarchive:
    dest: '{{ src_dir }}'
    group: '{{ whoami.stdout }}'
    owner: '{{ whoami.stdout }}'
    src: '{{ src_url }}'
    remote_src: true
  become: true
