---

- name: run whoami
  command: whoami
  changed_when: false
  register: whoami

- name: install Development Tools
  yum:
    name: "@Development Tools"
  become: true

- name: install dependencies
  yum:
    name:
      - gnutls-devel
      - ncurses-devel
  become: true

- name: check if difrectory to store Emacs source code exists
  stat:
    path: "{{ source_dir }}"
  become: true
  register: stat_source_dir

- name: make sure directory to store Emacs source code exists
  file:
    group: "{{ whoami.stdout }}"
    mode: 0775
    owner: "{{ whoami.stdout }}"
    path: "{{ source_dir }}"
    state: directory
  become: true
  when: not stat_source_dir.stat.exists

- name: download source code
  unarchive:
    creates: "{{ source_dir }}/emacs-{{ version }}"
    dest: "{{ source_dir }}"
    group: "{{ whoami.stdout }}"
    owner: "{{ whoami.stdout }}"
    remote_src: true
    src: https://ftp.gnu.org/pub/gnu/emacs/emacs-{{ version }}.tar.gz
  become: true
  notify: configure

- name: create directory for Emacs config file
  file:
    group: "{{ config_group }}"
    mode: 0700
    owner: "{{ config_owner }}"
    path: "{{ config_dir }}"
    state: directory
  become: true

- name: download config file
  get_url:
    dest: "{{ config_dir }}"
    group: "{{ config_group }}"
    mode: 0664
    owner: "{{ config_owner }}"
    url: "{{ config_url }}"
  become: true
